name: Build Docs

# https://stackoverflow.com/questions/63460875/github-actions-how-do-you-trigger-a-push-when-a-specific-directory-in-a-branch
on:
  # Able to run manually
  workflow_dispatch:

  # Runs when there are any changes to dev:docs/
  push:
    branches:
      - dev
    paths:
      - docs/**

  # Once on pull request FROM `*` TO `master`; this will be a required status check
  pull_request:
    branches:
      - master

jobs:
  build-docs:

    name: build-docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Build docs
        run: mkdocs build -s
